name: Give.Receive.Love
favicon: null
layout_spectrum: 0.7864352809265256
typography_spectrum: 0.34952806984074414
title: Give and Receive with Love
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.022694289218634367
  lightness: 0.19360370421782136
  saturation: 0.6776289064437151
  rhythmicContrast: 0.6782340744975954
purpose: []
